### ISSUE TITLE
App Drawer doesn't show any apps (Windows 11)

### ISSUE THREAD

**Issue by A-little-hedgehog** [Droptop-Four/Basic-Version#56] opened 2023-03-12 17:37 UTC
The app drawer button on droptop 4 doesn't show any aplications when open.

To reproduce 
Click the app drawer button in a Windows 11 machine

Expected behavior
The App drawer should display working apps

**Screenshots**
What it shows
![Captura de Tela (2)](https://user-images.githubusercontent.com/86445668/224562008-c34fdb6a-119f-45ff-9f91-58afff70758e.png)
The applications it should show
![Captura de Tela (5)](https://user-images.githubusercontent.com/86445668/224562150-f200f2eb-7969-48fd-b2a4-f18f0e75ee26.png)

Diagnostic: 
__**OS information**__

- OS: Windows 11 x64
- OSVERSION: 11
- Win10Apps: 0

__**Rainmeter information**__

- Skins path: %USERPROFILE%\Documents\Rainmeter\Skins\

- Program drive: C:
- Program path: C:\Program Files\Rainmeter\
- Settings path: %USERPROFILE%\AppData\Roaming\Rainmeter\
- Plugins path: C:\Program Files\Rainmeter\Plugins\
- Addons path: %USERPROFILE%\AppData\Roaming\Rainmeter\Addons\
- Config editor: C:\Program Files\WindowsApps\Microsoft.WindowsNotepad_11.2302.16.0_x64__8wekyb3d8bbwe\Notepad\Notepad.exe

__**Monitor information**__

- Primary screen area: 0, 0, 1920, 1080
- Screen area: 0, 0, 1920, 1080

- Primary work area: 0, 26, 1920, 1006
- Work area: 0, 26, 1920, 1006

- Virtual screen area: 0, 0, 1920, 1080

- Droptop on monitor: Primary

__**Droptop information**__

- Droptop version: 4.311.78.0
- Build date: 23.0312

- Height of top bar: 26
- Droptop scale: 1
- Currently using theme: Big Sur

- Droptop display mode: Always Show
- Accessibility in fullscreen: 0

__**App information**__

✅ Disks-Phan
❌ Quick_Settings-Cariboudjan
❌ Usage_Monitor-Cariboudjan
❌ Daily_Quotes-Bunz
❌ Sample_App-Cariboudjan

**Comment by 66Bunz** [comment] 2023-03-12 18:13
duplicate of #54 
we are working on it right now

**Closed by 66Bunz** 2023-03-12 18:13 UTC
Labels: duplicate
